//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: netmessage.proto
namespace netmessage
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CProto")]
    public partial class CProto : global::ProtoBuf.IExtensible
    {
        public CProto() { }

        private int _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _body;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string body
        {
            get { return _body; }
            set { _body = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CP1")]
    public partial class CP1 : global::ProtoBuf.IExtensible
    {
        public CP1() { }

        private int _a;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int a
        {
            get { return _a; }
            set { _a = value; }
        }
        private long _b;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public long b
        {
            get { return _b; }
            set { _b = value; }
        }
        private string _c;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"c", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string c
        {
            get { return _c; }
            set { _c = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CP2")]
    public partial class CP2 : global::ProtoBuf.IExtensible
    {
        public CP2() { }

        private string _a;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"a", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string a
        {
            get { return _a; }
            set { _a = value; }
        }
        private string _b;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"b", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string b
        {
            get { return _b; }
            set { _b = value; }
        }
        private long _c;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"c", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public long c
        {
            get { return _c; }
            set { _c = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}